new-session

unbind C-b
set -g prefix C-Space
bind Space send-prefix
bind C-Space next-window
bind C-d detach
bind C-c command-prompt -p command: "new-window -n '%1' '%1'"

# Options

set -g base-index 1
set -g pane-base-index 1
set -g set-titles on
set -g status-position top
set -g extended-keys on
set -g extended-keys-format csi-u

set -g default-terminal "tmux-256color"
set -ag terminal-features "tmux-256color:RGB"
set -ag terminal-features "xterm-ghostty:RGB"
set -ag terminal-features "xterm-256color:RGB"
set -ga update-environment " COLORTERM"

# Window options

set -gw mode-keys emacs
set -gw monitor-activity on
set -gw mouse on

# Scroll

bind -T copy-mode-vi WheelUpPane   send-keys -X -N 5 scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X -N 5 scroll-down
bind -T copy-mode WheelUpPane      send-keys -X -N 5 scroll-up
bind -T copy-mode WheelDownPane    send-keys -X -N 5 scroll-down

# Plugins

set -g @tpm_plugins '            \
tmux-plugins/tpm                 \
tmux-plugins/tmux-sensible       \
tmux-plugins/tmux-copycat        \
tmux-plugins/tmux-yank           \
tmux-plugins/tmux-urlview        \
tmux-plugins/tmux-fpp            \
'

run-shell '~/.tmux/plugins/tpm/tpm'
