#!/usr/bin/env zsh

typeset -A mapping
mapping=(
    .zshrc .zshrc
    .editrc .editrc
    .emacs.d .emacs.d
    .gitconfig .gitconfig
    .hgconcise .hgconcise
    .hgrc .hgrc
    .vimrc .vimrc
    DefaultKeyBinding.dict Library/KeyBindings/DefaultKeyBinding.dict
    ipython_config.py .ipython/profile_default/ipython_config.py
    .inputrc .inputrc
    .psqlrc .psqlrc
    lein-profiles.clj .lein/profiles.clj
    git-req bin/git-req
    .tmux.conf .tmux.conf
    .patdiff .patdiff
    net.solovyov.vpn.plist "Library/LaunchAgents/net.solovyov.vpn.plist"
    #net.solovyov.sshtun.plist "Library/LaunchAgents/net.solovyov.sshtun.plist"
    hammerspoon.lua .hammerspoon/init.lua
    karabiner.json .config/karabiner/karabiner.json
    joker .joker
    rc.elv .elvish/rc.elv
    )

for src in ${(k)mapping}; do
    dst=~/${mapping[$src]}
    if [ ! -L "$dst" ]; then
        echo "$src -> $dst"
        mkdir -p "$(dirname "$dst")"
        ln -s "$PWD/$src" "$dst"
    fi
done
