#!/usr/bin/env zsh

typeset -A mapping
mapping=(
    .zshrc .zshrc
    .editrc .editrc
    .emacs.d .emacs.d
    .gitconfig .gitconfig
    .hgconcise .hgconcise
    .hgrc .hgrc
    .vimrc .vimrc
    DefaultKeyBinding.dict Library/KeyBindings/DefaultKeyBinding.dict
    ipython_config.py .config/ipython/profile_default/ipython_config.py
    .inputrc .inputrc
    .psqlrc .psqlrc
    lein-profiles.clj .lein/profiles.clj
    git-req bin/git-req
    # LT/user.keymap "Library/Application Support/LightTable/settings/user.keymap"
    # LT/user.behaviors "Library/Application Support/LightTable/settings/user.behaviors"
    .tmux.conf .tmux.conf
    .patdiff .patdiff
    net.solovyov.runonwifi.plist "Library/LaunchAgents/net.solovyov.runonwifi.plist"
    karabiner.xml "Library/Application Support/Karabiner/private.xml"
    )

for src in ${(k)mapping}; do
    dst=~/${mapping[$src]}
    if [ ! -L "$dst" ]; then
        echo "$src -> $dst"
        mkdir -p "$(dirname "$dst")"
        ln -s "$PWD/$src" "$dst"
    fi
done
